name: mars-ic
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - obspy=1.4.1
  - numpy=1.26.4
  - scipy=1.13.1
  - dynesty=2.1.5
  - emcee=3.1.6
  - pandas=2.2.2
  - matplotlib=3.9.2
  - openpyxl=3.1.5
  - pyyaml=6.0.2
  - pytest=8.3.2
  - setuptools=80.9.0
  - tk=8.6.13
  - jupyter=1.1.1
  - tqdm=4.66.5
  - pip:
    - func-timeout==4.3.5
